### ISSUE TITLE
Be less opinionated about the deprecation warning

### ISSUE THREAD

**Issue by thomaseizinger** [ggwpez/proc-macro-warning#3]
At the moment, the crate is quite opinionated on how the warning should be generated. I'd like to ask if we can have more control over the provided message?

Personally, I'd just like to write the entire content of `#[deprecated(note = "")]` myself.

See [libp2p/rust-libp2p@`25deeb9` (#3848)](https://github.com/libp2p/rust-libp2p/pull/3848/commits/25deeb9c09b402cab60a995464594aa9cb111551) for some context.

**Comment by ggwpez** [comment]
Yea I agree. It is possible to directly create `Warning::new_raw`, but it will still put line breaks in there.  
I will create a minimal `FormattedWarning` that just pastes the `note` in there.

**Comment by ggwpez** [comment]
Going to re-open until you confirm, added `FormattedWarning::new_deprecated(name, note, span)` see [README](https://github.com/ggwpez/proc-macro-warning#un-opinionated-formatting).

**Comment by ggwpez** [comment]
Confirmed to work in https://github.com/libp2p/rust-libp2p/pull/3921
